from alembic import op
import sqlalchemy as sa
# Import TIMESTAMP from sqlalchemy.dialects.postgresql if you want to be explicit for PostgreSQL
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '<your_new_revision_id_here>'  # This will be filled in by Alembic
down_revision = '72dccd5d1a8b' # This will be filled in by Alembic
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs',  # Your table name (from Job.__tablename__)
        sa.Column(
            'last_updated_ts', 
            postgresql.TIMESTAMP(timezone=True), # Explicitly using postgresql.TIMESTAMP
            server_default=sa.text('CURRENT_TIMESTAMP'), # Database-level default for new rows
            nullable=True # Or False if you want to ensure it's always populated. 
        )
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_updated_ts')
    # ### end Alembic commands ###