from transformers import AutoTokenizer, AutoModelForSequenceClassification
from peft import PeftModel

# Load base model and LoRA adapter
base_model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
model = PeftModel.from_pretrained(base_model, "./lora_adapter")
tokenizer = AutoTokenizer.from_pretrained("./lora_adapter")

# Define 10 sample input texts (manually created)
sample_texts = [
    "Senior ReactJS developer with experienced",
    "Full-stack engineer with Node.js and Express.js skills. [SEP] Hiring frontend React.js developer for e-commerce portal.",
    "Data scientist specializing in machine learning models. [SEP] Hiring a mobile app developer experienced in Flutter.",
    "DevOps engineer with Kubernetes and AWS EKS expertise. [SEP] Hiring a data scientist with TensorFlow experience.",
    "Mobile app developer skilled in React Native and Redux. [SEP] Looking for a frontend developer specializing in Vue.js.",
    "Experienced Django backend engineer with REST API experience. [SEP] Hiring for a Flutter mobile engineer role.",
    "Cybersecurity analyst with OSCP certification and audits. [SEP] Hiring a backend Node.js developer for API development.",
    "React developer proficient in Next.js and Tailwind CSS. [SEP] Looking for a React Native mobile app engineer.",
    "Software tester with Selenium and Playwright skills. [SEP] Hiring a machine learning engineer for vision models.",
    "Full-stack MERN developer building SaaS products. [SEP] Hiring a data engineer with Spark and Hadoop expertise.",
    "AI engineer with expertise in HuggingFace Transformers. [SEP] Hiring a frontend engineer experienced with Ant Design.",
    "Mobile engineer with Android Kotlin and Jetpack skills. [SEP] Hiring backend engineer for GoLang and gRPC microservices.",
    "Backend engineer focused on GraphQL and Prisma. [SEP] Hiring React.js frontend engineer for admin panel development.",
    "Senior AWS cloud architect with serverless expertise. [SEP] Hiring cybersecurity specialist for cloud security audits.",
    "Junior React.js developer with experience in Redux Toolkit. [SEP] Hiring mobile app engineer skilled in Flutter and Dart.",
    "Python engineer specialized in FastAPI microservices. [SEP] Hiring frontend engineer with React.js and styled-components.",
    "DevOps engineer with Helm, Terraform, and Jenkins skills. [SEP] Hiring backend engineer experienced in Django ORM.",
    "Node.js backend developer experienced in building RESTful APIs. [SEP] Hiring a data scientist skilled in PyTorch.",
    "Machine learning engineer building vision models with PyTorch. [SEP] Hiring frontend Vue.js engineer for data dashboard.",
    "Flutter developer with Firebase and Redux experience. [SEP] Hiring Node.js backend developer for payment system integration.",
    "Full-stack JavaScript developer skilled in React and Express. [SEP] Hiring cybersecurity engineer for vulnerability analysis.",
    "iOS SwiftUI developer with mobile apps background. [SEP] Hiring frontend web developer with Vue.js and Bootstrap.",
    "DevOps specialist with Docker Swarm and Kubernetes clusters. [SEP] Hiring mobile developer experienced in React Native.",
    "Data engineer skilled in BigQuery and Snowflake pipelines. [SEP] Hiring a frontend engineer skilled in Material UI.",
    "NLP research scientist working on BERT fine-tuning. [SEP] Hiring a Node.js backend engineer for APIs optimization.",
    "Cybersecurity pentester experienced in network hardening. [SEP] Hiring a React frontend engineer for UI feature development.",
    "React Native developer with Expo and Redux Toolkit. [SEP] Hiring a Django backend engineer for API development.",
    "Software developer focused on Flask and FastAPI systems. [SEP] Hiring mobile developer with Flutter and Firebase stack.",
    "Cloud DevOps engineer with AWS CDK experience. [SEP] Hiring a frontend engineer specializing in React and Next.js.",
    "Senior MERN stack developer building scalable systems. [SEP] Hiring a data scientist with focus on predictive modeling.",
    "NLP specialist developing chatbots using Rasa and Huggingface. [SEP] Hiring frontend Vue.js engineer for analytics dashboard.",
    "AI/ML engineer fine-tuning Transformer LLM models. [SEP] Hiring cybersecurity analyst for compliance monitoring.",
    "Mobile app engineer with Android native app deployment. [SEP] Hiring backend engineer skilled in Go and PostgreSQL.",
    "Senior Vue.js engineer leading frontend projects. [SEP] Hiring backend engineer specialized in GraphQL APIs.",
    "Backend engineer with expertise in Django and Celery queues. [SEP] Hiring frontend engineer specializing in Tailwind CSS designs.",
    "DevOps engineer with experience in ArgoCD and GitOps. [SEP] Hiring mobile developer with React Native expertise.",
    "Data scientist skilled in unsupervised clustering algorithms. [SEP] Hiring React.js frontend engineer for CRM platform.",
    "Experienced Android developer proficient in Kotlin Multiplatform. [SEP] Hiring a backend Node.js engineer for RESTful APIs.",
    "Machine learning scientist working on recommender systems. [SEP] Hiring frontend web developer skilled in Chakra UI.",
    "React Native engineer with Firebase Realtime Database knowledge. [SEP] Hiring cybersecurity specialist for mobile app audits.",
    "Python backend engineer with Django ORM and Redis caching. [SEP] Hiring Flutter developer for mobile shopping app.",
    "Cloud architect with AWS, Azure, and GCP certifications. [SEP] Hiring data engineer with Hadoop MapReduce experience.",
    "Frontend engineer specialized in React Query and Tailwind UI. [SEP] Hiring backend developer with Node.js and Express.js experience.",
    "Flutter mobile developer experienced with GetX state management. [SEP] Hiring React.js developer for SaaS frontend dashboard.",
    "DevOps automation engineer with Ansible and Chef experience. [SEP] Hiring frontend web developer skilled in Vue.js 3.",
    "iOS mobile app developer experienced in Swift Combine patterns. [SEP] Hiring a backend engineer with Node.js and MongoDB stack.",
    "React frontend developer specializing in animation libraries. [SEP] Hiring backend engineer skilled in Django and GraphQL APIs.",
    "Cybersecurity blue team analyst monitoring SIEM logs. [SEP] Hiring frontend React developer for UI dashboard refresh.",
    "Backend engineer with NestJS and PostgreSQL experience. [SEP] Hiring mobile developer experienced in React Native CLI.",
    "AI engineer building GAN models for image generation. [SEP] Hiring frontend web engineer focused on Chakra UI and React.",
]


sample_texts += [
    "Senior cybersecurity analyst with SIEM and threat intel experience. [SEP] Hiring a frontend engineer skilled in React and Material UI.",
    "Mobile app developer specialized in Flutter and Firebase. [SEP] Looking for a DevOps engineer experienced with AWS and Docker.",
    "Data scientist with a strong background in NLP pipelines. [SEP] Hiring frontend developer with Vue.js and Tailwind CSS skills.",
    "Backend engineer proficient in Java Spring Boot. [SEP] Hiring React developer with Redux Toolkit and component library expertise.",
    "React frontend engineer with design system experience. [SEP] Hiring mobile app developer with Flutter and Firebase integration.",
    "DevOps expert with Kubernetes and Helm chart deployments. [SEP] Hiring data engineer with Spark and Hadoop proficiency.",
    "AI/ML engineer working on LLM fine-tuning with LoRA. [SEP] Hiring frontend engineer with Chakra UI and styled-components.",
    "Vue.js developer with Nuxt and SSR knowledge. [SEP] Hiring backend engineer experienced with Django and Redis.",
    "Node.js backend engineer with Express.js and MongoDB. [SEP] Hiring mobile app developer with React Native background.",
    "Junior Python developer working on microservices. [SEP] Hiring cybersecurity analyst for system hardening and audits.",
    "Machine learning engineer developing recommendation systems. [SEP] Hiring frontend developer experienced in React Query.",
    "React.js frontend developer with accessibility focus. [SEP] Hiring backend GoLang developer for scalable microservices.",
    "Flutter app developer experienced in cross-platform apps. [SEP] Hiring cybersecurity engineer for mobile app security.",
    "Django backend developer with PostgreSQL optimization experience. [SEP] Hiring frontend Vue 3 developer for real-time dashboards.",
    "React Native engineer focused on app performance. [SEP] Hiring a backend engineer experienced in Java Spring Boot APIs.",
    "Senior DevOps engineer automating infrastructure. [SEP] Hiring data scientist with Pandas and Scikit-learn skills.",
    "Mobile app engineer with iOS SwiftUI experience. [SEP] Hiring a React frontend developer for admin dashboard builds.",
    "Cloud DevOps engineer with AWS CDK and GitHub Actions. [SEP] Hiring a frontend developer specializing in Next.js.",
    "Data analyst proficient in Power BI and SQL analytics. [SEP] Hiring a backend engineer with Node.js and MongoDB skills.",
    "React frontend developer skilled in Chakra UI and Framer Motion. [SEP] Hiring a backend engineer with Django DRF stack.",
    "Python developer with Flask and Celery queue experience. [SEP] Hiring mobile app engineer with Flutter and Dart skills.",
    "Software engineer focused on React/Redux frontend apps. [SEP] Hiring cybersecurity engineer to lead network audits.",
    "AWS architect experienced in serverless Lambda systems. [SEP] Hiring frontend Vue.js developer for finance dashboard.",
    "NLP engineer with Hugging Face Transformers training. [SEP] Hiring backend engineer for Django and Redis integration.",
    "Mobile app developer skilled in Kotlin and Jetpack Compose. [SEP] Hiring a React developer for browser-based SPA.",
    "DevOps engineer with Jenkins and Docker Compose pipelines. [SEP] Hiring a mobile app developer for iOS/Android platform.",
    "AI engineer fine-tuning BERT for classification tasks. [SEP] Hiring frontend web developer for React + Tailwind project.",
    "Senior backend developer experienced in Go and Redis. [SEP] Hiring frontend React engineer with design system exposure.",
    "Cybersecurity red team member with OSCP and Burp Suite. [SEP] Hiring a frontend engineer for e-commerce UX design.",
    "Backend Node.js developer with Prisma and GraphQL stack. [SEP] Hiring a mobile app engineer with Flutter and GetX.",
    "Senior React frontend engineer building complex dashboards. [SEP] Hiring backend developer with Flask and PostgreSQL skills.",
    "Android engineer with Kotlin and Realm DB experience. [SEP] Hiring frontend developer skilled in Vue.js and Vite.",
    "Cloud-native DevOps engineer working with Terraform. [SEP] Hiring AI engineer with Transformers and self-supervised learning.",
    "Data engineer experienced with Kafka and Airflow. [SEP] Hiring frontend developer with React and D3.js visualization skills.",
    "Flutter mobile developer with cross-platform delivery apps. [SEP] Hiring a cybersecurity analyst for application security reviews.",
    "React.js developer experienced in Tailwind and Zustand. [SEP] Hiring a backend developer with Django and Celery background.",
    "Cybersecurity specialist focused on system penetration testing. [SEP] Hiring mobile developer with Flutter and Firebase support.",
    "Machine learning researcher focused on unsupervised learning. [SEP] Hiring React frontend developer for product analytics UI.",
    "Frontend Vue.js developer working with Nuxt and Vite. [SEP] Hiring backend engineer for Python Django ecommerce APIs.",
    "Python developer working on REST APIs and OpenAPI specs. [SEP] Hiring mobile engineer experienced in Flutter and Clean Architecture.",
    "MERN stack engineer building full SaaS systems. [SEP] Hiring a DevOps engineer to manage CI/CD and container orchestration.",
    "React Native developer with payment integration experience. [SEP] Hiring a data scientist with PyTorch and MLFlow exposure.",
    "React.js developer with Ant Design and enterprise UIs. [SEP] Hiring backend engineer for Spring Boot microservices APIs.",
    "Backend Java developer with gRPC and GraphQL stack. [SEP] Hiring frontend engineer with React and TypeScript expertise.",
    "Flutter mobile app engineer focused on startup MVPs. [SEP] Hiring cybersecurity expert for API token encryption system.",
    "Node.js backend engineer working on scalable APIs. [SEP] Hiring mobile developer skilled in Flutter and Firebase Realtime.",
    "Cloud DevOps engineer deploying to EKS and Fargate. [SEP] Hiring frontend developer with React and Material UI experience.",
    "Mobile app engineer focused on health tech. [SEP] Hiring backend developer for Django and PostgreSQL patient data system.",
    "Full-stack developer with Vue.js and Django REST stack. [SEP] Hiring React Native developer for cross-platform rollout.",
    "Data scientist specializing in fraud detection. [SEP] Hiring frontend engineer experienced in React and high-performance charts.",
]



# sample_texts += [
#     "Senior React.js developer building UI dashboards. [SEP] Hiring a cybersecurity analyst to lead network defense.",
#     "Machine learning engineer with experience in recommendation systems. [SEP] Looking for React Native mobile app developer.",
#     "Cybersecurity expert in risk audits and threat detection. [SEP] Hiring frontend engineer with React and Redux Toolkit.",
#     "Flutter developer focused on mobile banking apps. [SEP] Hiring backend developer skilled in Go and PostgreSQL.",
#     "Senior Node.js engineer building scalable REST APIs. [SEP] Hiring mobile engineer with Flutter and Firebase experience.",
#     "Full-stack MERN developer creating eCommerce platforms. [SEP] Hiring React frontend developer for product detail UIs.",
#     "Django backend engineer with Celery task queue knowledge. [SEP] Hiring DevOps engineer with Kubernetes and Helm experience.",
#     "Android developer with Jetpack Compose and MVVM. [SEP] Hiring cybersecurity specialist for mobile network monitoring.",
#     "Cloud engineer with AWS CDK and CI/CD automation. [SEP] Hiring frontend Vue.js developer for SaaS dashboard.",
#     "AI/ML engineer building semantic search systems. [SEP] Hiring React Native developer for marketplace mobile apps.",
#     "Frontend engineer skilled in React and Storybook. [SEP] Hiring data engineer for ETL and pipeline optimization.",
#     "Backend engineer using Spring Boot and Kafka. [SEP] Hiring a Flutter developer for health app MVP.",
#     "Python developer with FastAPI and Pydantic experience. [SEP] Hiring frontend developer with Vue 3 and Pinia.",
#     "Cybersecurity red team specialist with OSCP cert. [SEP] Hiring React.js engineer for security admin panel.",
#     "Mobile app engineer focused on cross-platform apps. [SEP] Hiring backend engineer with Django and PostgreSQL.",
#     "Cloud DevOps engineer managing EKS and Terraform. [SEP] Hiring mobile developer experienced in Flutter and BLoC.",
#     "NLP specialist with Hugging Face Transformers. [SEP] Hiring frontend engineer skilled in Next.js and React Query.",
#     "Senior backend engineer using GoLang and gRPC. [SEP] Hiring mobile developer for Flutter and Firebase platform.",
#     "DevOps engineer with Jenkins and GitHub Actions. [SEP] Hiring cybersecurity analyst with SIEM and threat modeling.",
#     "Frontend React developer with accessibility focus. [SEP] Hiring backend engineer with Python and Django REST.",
#     "Data scientist with focus on anomaly detection. [SEP] Hiring Flutter engineer for cross-platform logistics app.",
#     "React Native engineer for social media apps. [SEP] Hiring backend Node.js developer for real-time APIs.",
#     "Full-stack developer using Vue.js and Firebase. [SEP] Hiring data scientist for churn prediction model.",
#     "Backend engineer focused on Express and MongoDB. [SEP] Hiring frontend developer with React and Tailwind CSS.",
#     "AI/ML researcher training LLMs on medical data. [SEP] Hiring mobile app developer for iOS and Android.",
#     "DevOps engineer automating workflows with Ansible. [SEP] Hiring a Flutter engineer for grocery delivery app.",
#     "iOS developer experienced in SwiftUI and CoreML. [SEP] Hiring backend engineer with NestJS and TypeORM.",
#     "Cybersecurity penetration tester with bug bounty wins. [SEP] Hiring frontend React developer for audit tools.",
#     "Android app developer using Kotlin and MVVM. [SEP] Hiring backend Django developer with DRF and PostgreSQL.",
#     "AI engineer building chatbots with Rasa and GPT. [SEP] Hiring mobile app developer for Flutter frontends.",
#     "Python developer using Flask and Redis caching. [SEP] Hiring frontend Vue.js developer for analytics dashboards.",
#     "React frontend engineer with design systems expertise. [SEP] Hiring DevOps engineer with AWS and Helm experience.",
#     "DevOps architect working with GitOps and ArgoCD. [SEP] Hiring frontend developer with Chakra UI and TypeScript.",
#     "Cybersecurity SOC analyst monitoring real-time alerts. [SEP] Hiring backend developer with Django ORM.",
#     "Machine learning engineer building computer vision tools. [SEP] Hiring mobile app engineer for React Native.",
#     "Backend developer using GoLang and Redis. [SEP] Hiring React.js frontend engineer for dashboard interface.",
#     "Cloud engineer with GCP and Pub/Sub messaging. [SEP] Hiring a Flutter developer for productivity app.",
#     "AI researcher working on multi-modal learning. [SEP] Hiring frontend Vue 3 engineer with composition API.",
#     "Mobile engineer developing chat apps in React Native. [SEP] Hiring backend engineer for Node.js microservices.",
#     "Django developer with ORM optimization skills. [SEP] Hiring Flutter developer for job search platform.",
#     "Frontend engineer with React and Recharts. [SEP] Hiring data engineer to manage Snowflake pipelines.",
#     "Senior cybersecurity expert on compliance tools. [SEP] Hiring React.js developer for audit dashboard.",
#     "Python developer using FastAPI and SQLModel. [SEP] Hiring mobile app developer with Flutter experience.",
#     "Android engineer building offline-first apps. [SEP] Hiring backend Node.js engineer for video streaming APIs.",
#     "MERN stack developer focused on B2B platforms. [SEP] Hiring cybersecurity engineer for internal threat scans.",
#     "React frontend developer with animation libraries. [SEP] Hiring Django engineer for ecommerce backend.",
#     "Backend Java engineer using Spring Data JPA. [SEP] Hiring React Native mobile app engineer for dating app.",
#     "Cybersecurity blue team analyst with IDS tools. [SEP] Hiring frontend developer with Tailwind CSS skills.",
#     "AI/ML engineer with TensorFlow Serving deployment. [SEP] Hiring frontend developer with Next.js and GraphQL.",
#     "Mobile developer using Flutter and Clean Architecture. [SEP] Hiring backend Node.js engineer for checkout API.",
#     "DevOps engineer building monitoring tools with Prometheus. [SEP] Hiring frontend React.js engineer for alerting UI.",
#     "Django REST developer with JWT token integration. [SEP] Hiring React Native engineer for fitness tracker app.",
#     "Backend Node.js developer using Apollo Server. [SEP] Hiring frontend Vue.js engineer with charting skills.",
#     "iOS developer with ARKit and SwiftUI experience. [SEP] Hiring Django backend developer for ecommerce API.",
#     "Cloud engineer with multi-cloud deployment experience. [SEP] Hiring mobile Flutter developer for task manager app.",
#     "React.js developer using Material UI and Zustand. [SEP] Hiring backend engineer with Python and Celery.",
#     "Data scientist developing forecasting models. [SEP] Hiring React Native developer for event app development.",
#     "Cybersecurity consultant conducting infrastructure audits. [SEP] Hiring backend developer for REST API buildout.",
#     "NLP engineer working with OpenAI APIs. [SEP] Hiring frontend engineer with React and Chakra UI.",
#     "React Native mobile app engineer with Redux. [SEP] Hiring a data engineer with Hadoop and Hive experience.",
#     "DevOps engineer deploying on AWS ECS. [SEP] Hiring frontend Vue.js engineer with Tailwind and Pinia.",
#     "Full-stack engineer with Express and Vue.js. [SEP] Hiring cybersecurity analyst with risk modeling experience.",
#     "Senior backend developer with Django and PostgreSQL. [SEP] Hiring mobile app engineer for React Native MVP.",
#     "Android developer using Firebase and Room DB. [SEP] Hiring React frontend engineer for SEO-friendly UI.",
#     "Flutter mobile engineer with push notification setup. [SEP] Hiring a backend developer with Django and Redis.",
#     "AI researcher training vision models on large datasets. [SEP] Hiring a mobile developer for React Native chat apps.",
#     "Node.js engineer with Prisma and PostgreSQL experience. [SEP] Hiring a cybersecurity analyst for internal audits.",
#     "Python developer working on API rate-limiting tools. [SEP] Hiring frontend React engineer with Ant Design skills.",
#     "React Native developer building cross-platform social apps. [SEP] Hiring a backend engineer with Spring Boot and Hibernate.",
#     "Machine learning engineer developing fraud detection models. [SEP] Hiring a React frontend engineer for reporting interface.",
#     "Backend developer using Fastify and MySQL. [SEP] Hiring Flutter mobile engineer for gig marketplace app.",
#     "DevOps engineer building CI/CD pipelines in GitHub Actions. [SEP] Hiring React frontend developer for booking system.",
#     "Cybersecurity engineer working on cloud identity. [SEP] Hiring full-stack MERN developer for internal tool.",
#     "Full-stack engineer working in Python and React. [SEP] Hiring a Flutter developer for travel app.",
#     "React.js developer focused on dynamic UIs. [SEP] Hiring backend engineer with Django and PostgreSQL.",
#     "Data engineer using Airflow and BigQuery. [SEP] Hiring frontend Vue.js developer with analytics dashboard skills.",
#     "NLP engineer using spaCy and Sentence Transformers. [SEP] Hiring mobile app developer with Flutter and Redux.",
#     "Senior mobile engineer with React Native expertise. [SEP] Hiring backend developer for Node.js and GraphQL.",
#     "React.js developer building drag-and-drop tools. [SEP] Hiring DevOps engineer for AWS and Terraform.",
#     "Java backend engineer building microservices. [SEP] Hiring frontend React developer with Framer Motion.",
#     "Cybersecurity analyst doing pentests and reverse engineering. [SEP] Hiring mobile app engineer with Flutter stack.",
#     "iOS developer working with Combine and SwiftUI. [SEP] Hiring React Native engineer for cross-platform MVP.",
#     "Django backend engineer building B2C APIs. [SEP] Hiring frontend engineer with Vue 3 and charting libraries.",
#     "AI engineer working with large language models. [SEP] Hiring mobile app developer skilled in Flutter and Dart.",
#     "Full-stack TypeScript developer using Next.js and NestJS. [SEP] Hiring cybersecurity analyst for API security.",
#     "Python engineer building NLP classifiers. [SEP] Hiring frontend developer with React and CSS-in-JS tools.",
#     "Senior DevOps engineer managing multi-cloud environments. [SEP] Hiring frontend developer with Vue and Storybook.",
#     "Data scientist building time series forecasting. [SEP] Hiring mobile app engineer for React Native banking apps.",
#     "Mobile app developer with Flutter BLoC experience. [SEP] Hiring a backend engineer with Django DRF.",
#     "Cloud engineer using AWS SAM and serverless framework. [SEP] Hiring frontend React.js engineer for forms interface.",
#     "Cybersecurity engineer working with WAF and VPNs. [SEP] Hiring React frontend developer with dashboard skills.",
#     "AI/ML specialist fine-tuning GPT-3 models. [SEP] Hiring mobile Flutter developer for news reader app.",
#     "Vue.js engineer working on admin dashboards. [SEP] Hiring backend Node.js developer with GraphQL integration.",
#     "Senior software engineer building REST and GraphQL APIs. [SEP] Hiring mobile app engineer with React Native and Firebase.",
#     "Python backend developer with Django, Redis, and Celery. [SEP] Hiring frontend engineer with React Query and MUI.",
#     "AI researcher using LoRA for parameter-efficient tuning. [SEP] Hiring cybersecurity analyst to secure LLM outputs.",
# ]


# Tokenize the list of inputs in batch
inputs = tokenizer(sample_texts, return_tensors="pt", padding=True, truncation=True)

# Run predictions
outputs = model(**inputs)
predictions = outputs.logits.argmax(dim=-1)

# Print results
for i, (text, pred) in enumerate(zip(sample_texts, predictions)):
    print(f"{i+1}. Text: {text}")
    print(f"   Predicted class: {pred.item()}\n")